### ISSUE TITLE
Repo obsolete or move into perception_pcl branch -- Archive (or delete as to not confuse)? 

### ISSUE THREAD

**Issue by SteveMacenski** [ros2/pcl_conversions#5]

**Comment by clalancette** [comment]
So, as it stands, we still release this repository into Dashing for the perception_pcl package: https://github.com/ros/rosdistro/blob/master/dashing/distribution.yaml#L880 .  I guess upstream does have a crystal-devel branch, but I have no idea of the state or what has been ported there.  I'm happy to deprecate this repo once we figure out what is going on there.  @SteveMacenski can you take a look and make sure all of the changes here are present upstream?  Thanks.

**Comment by SteveMacenski** [comment]
Good to know, I'll add this to my queue to figure out the state of both of these, what's missing, and port over. Might be a few weeks before I get to it. 

(this is part of my waging war against duplicate repositories)

**Comment by mabelzhang** [comment]
I resolved the diff between the ros2 branch of this repo and this perception_pcl PR port to Dashing https://github.com/ros-perception/perception_pcl/pull/244

If someone from here could give it a review and check that everything from here is there, that would be great.

**Comment by SteveMacenski** [comment]
Thanks for poking, I just did

**Comment by wjwwood** [comment]
@mabelzhang can this be closed?

**Comment by mabelzhang** [comment]
@SteveMacenski might have a better idea. 
The combining of `pcl_conversions` here with `perception_pcl` is still an active PR.
We are also actively working on porting `pcl_ros` and the plan is still to close this repo and release `perception_pcl` hopefully in Eloquent.

**Comment by clalancette** [comment]
To close this out we need:

- [x] ros-perception/perception_pcl#244 merged
~~- [ ] (maybe) ros-perception/perception_pcl#229 merged~~
- [x] ros-perception/perception-pcl released into Dashing
- [x] ros-perception/perception-pcl released into Eloquent
- [x] A final commit to this repository to decommission it (#7)
- [x] Archive this repository

**Comment by SteveMacenski** [comment]
I agree with @clalancette ‘s list

Though the maybe isnt required for feature parity to execute on the rest of this. That’s to actually finish all the pcl porting. 

Once we can get 244 in, I’ll immediately turn around and release to dashing/eloquent & remove this repo’s entry from the yaml files. @clalancette do you prefer to do the final commit stuff here?

**Comment by SteveMacenski** [comment]
@clalancette @mabelzhang https://github.com/ros/rosdistro/pull/23166 will move ownership in Dashing (later eloquent after merged) to pcl perception. This repo is ready for deprecation/archive.

**Comment by SteveMacenski** [comment]
https://github.com/ros/rosdistro/pull/23166
https://github.com/ros/rosdistro/pull/23194

Dashing and Eloquent have been changed to `perception_pcl` and removed `ros2/pcl_conversions`

I think this is good now for @clalancette to decommission this repo and archive it.

**Comment by clalancette** [comment]
Sorry, I've been slammed the last couple of weeks.  I'll try to get to it this week.

**Comment by SteveMacenski** [comment]
No worries, just a heads up

**Comment by clalancette** [comment]
All right, I've decommissioned this repository.  I'm going to close this issue out before archiving it.
