### ISSUE TITLE
toROSMsg cause data losing

### ISSUE THREAD

**Issue by jdclzl** [ros2/pcl_conversions#6]
I am tring to write a roi filter of velodyne_points data.As a simplest demo,i just use a fromROSMsg and toROSMsg function with a same ptr named pcl_cloud,but only this cause a data losing bug.In rviz ,the topic "velodyne_points" seems nomal,but "velodyne_points_out" only has a few points which looks like a single line. here is my code,can anyone help me?  
```cpp
class LidarROIFilter : public rclcpp::Node
{
public:
  LidarROIFilter()
      : Node("LidarROIFilter")
  {
    using std::placeholders::_1;
    pub_=this->create_publisher<sensor_msgs::msg::PointCloud2>("velodyne_points_out");
    subscription_ = this->create_subscription<sensor_msgs::msg::PointCloud2>(
        "velodyne_points", std::bind(&LidarROIFilter::topic_callback, this, _1));
  }
private:
void topic_callback(const sensor_msgs::msg::PointCloud2::SharedPtr msg)
  {
   
    pcl::PointCloud<pcl::PointXYZ>::Ptr pcl_cloud (new pcl::PointCloud<pcl::PointXYZ>);
    pcl::fromROSMsg(*msg, *pcl_cloud);
    sensor_msgs::msg::PointCloud2  outmsg;    
    pcl::toROSMsg(*pcl_cloud,outmsg);
    outmsg.header=msg->header;
    pub_->publish(outmsg);


  }
  rclcpp::Subscription<sensor_msgs::msg::PointCloud2>::SharedPtr subscription_;
  rclcpp::Publisher<sensor_msgs::msg::PointCloud2>::SharedPtr pub_;
};
```

**Comment by jdclzl** [comment]
i have solved this problem ,it is because there is some thing wrong with my velodyne-dashing driver.
the msg come out of the driver without a row_step,so i add this 
```
msg->row_step = msg->data.size() / msg->height;
```
problem solved

**Comment by clalancette** [comment]
Glad you were able to find the fix.  However, it is a bit weird that there was no `row_step` coming out of the velodyne; it very explicitly sets it at https://github.com/ros-drivers/velodyne/blob/dashing-devel/velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h#L80 .  Can you elaborate which driver you are using, and what value `row_step` was being set to?

**Comment by jdclzl** [comment]
> Glad you were able to find the fix. However, it is a bit weird that there was no `row_step` coming out of the velodyne; it very explicitly sets it at https://github.com/ros-drivers/velodyne/blob/dashing-devel/velodyne_pointcloud/include/velodyne_pointcloud/datacontainerbase.h#L80 . Can you elaborate which driver you are using, and what value `row_step` was being set to?

Thanks for your reply!
I was using the same velodyne-dashing driver,but the **row_step** was always 0.
The velodyne type i use is VLP-16.Since i did not figure out how to set the parameters of this driver_(the driver keeps ros1 lanch files and no ros2 param yaml file )_,so i directly write the parameters into the driver.cc file like this:
```cpp
std::string devip = this->declare_parameter("device_ip", std::string("192.168.1.201"));
...
config_.model = this->declare_parameter("model", std::string("VLP16")); 
```
To fix this issue，
i also add“**cloud.row_step = cloud.width * cloud.point_step;**”into **virtual void setup(const velodyne_msgs::msg::VelodyneScan::SharedPtr scan_msg)** function in **datacontainerbase.h** 
I am not sure if this is necessary.

**Comment by clalancette** [comment]
I know it has been a while here, but I took another look at this and I think I see the problem.  We were setting up the `row_step` too early, when `cloud.width` was still zero, so it was always zero.  I've now opened https://github.com/ros-drivers/velodyne/pull/291 which should fix the issue.  If you get a chance, please test that out and provide feedback on that pull request.  Thanks!
